// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rtimv.proto

#include "rtimv.pb.h"
#include "rtimv.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace remote_rtimv {

static const char* rtimv_method_names[] = {
  "/remote_rtimv.rtimv/Configure",
};

std::unique_ptr< rtimv::Stub> rtimv::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< rtimv::Stub> stub(new rtimv::Stub(channel, options));
  return stub;
}

rtimv::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Configure_(rtimv_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status rtimv::Stub::Configure(::grpc::ClientContext* context, const ::remote_rtimv::Config& request, ::remote_rtimv::ConfigResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::remote_rtimv::Config, ::remote_rtimv::ConfigResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Configure_, context, request, response);
}

void rtimv::Stub::async::Configure(::grpc::ClientContext* context, const ::remote_rtimv::Config* request, ::remote_rtimv::ConfigResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::remote_rtimv::Config, ::remote_rtimv::ConfigResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Configure_, context, request, response, std::move(f));
}

void rtimv::Stub::async::Configure(::grpc::ClientContext* context, const ::remote_rtimv::Config* request, ::remote_rtimv::ConfigResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Configure_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::remote_rtimv::ConfigResult>* rtimv::Stub::PrepareAsyncConfigureRaw(::grpc::ClientContext* context, const ::remote_rtimv::Config& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::remote_rtimv::ConfigResult, ::remote_rtimv::Config, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Configure_, context, request);
}

::grpc::ClientAsyncResponseReader< ::remote_rtimv::ConfigResult>* rtimv::Stub::AsyncConfigureRaw(::grpc::ClientContext* context, const ::remote_rtimv::Config& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConfigureRaw(context, request, cq);
  result->StartCall();
  return result;
}

rtimv::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      rtimv_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< rtimv::Service, ::remote_rtimv::Config, ::remote_rtimv::ConfigResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](rtimv::Service* service,
             ::grpc::ServerContext* ctx,
             const ::remote_rtimv::Config* req,
             ::remote_rtimv::ConfigResult* resp) {
               return service->Configure(ctx, req, resp);
             }, this)));
}

rtimv::Service::~Service() {
}

::grpc::Status rtimv::Service::Configure(::grpc::ServerContext* context, const ::remote_rtimv::Config* request, ::remote_rtimv::ConfigResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace remote_rtimv

