name: Compile rtimv
on:
  push:
      branches:
          - 'add-ci'
  schedule:
      - cron: '43 5 * * *'
jobs:
  install-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      env:
        MAGAOX_ROLE: ci
        NEEDRESTART_SUSPEND: 'yes'
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Fetch package definitions
        run: 'apt-get update'
      - name: Install basic prerequisites
        run: 'apt-get install -y git sudo build-essential'
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: 'bash -x scripts/rtimv_provision_ubuntu2204.sh'
        name: Test compilation script
